services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./docker_data/prometheus:/prometheus
    restart: always
  grafana:
    image: grafana/grafana
    volumes:
      - ./docker_data/grafana_data:/var/lib/grafana
    restart: always
    ports:
      - 3000:3000
