# Use root/example as user/password credentials
version: '3.1'

services:

  great_deku:
    image: mongo:8.0
    restart: always
    env_file: 
    - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ${MONGO_DATA_PERSISTENT}:/data/db
    ports:
      - 27017:27017
