services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    env_file:
      - .env
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
      - ${PROMETHEUS_VOLUME_PATH}:/prometheus
    restart: always
  grafana:
    image: grafana/grafana
    volumes:
      - ${GRAFANA_VOLUME_PATH}:/var/lib/grafana
    restart: always
    ports:
      - 3000:3000
